### ISSUE TITLE
Crear un bot de rols que permeti canviar el color del teu nom automaticament així com els teus pronoms. 

### ISSUE THREAD

**Issue by Laureliana** [vicky5124/Ciberbot-Transfemeni#9]
La meva proposta està dividida en dues parts, però tenen molta relació, així que per això ho poso en un:

D'una banda, crear un bot de rols al cibercasal, que permeti seleccionar el teu rol de color de forma automatica, on al clickar la opció desitjada,  sense necessitat de demanar-ho a una admin. 
Exemple: 
Entres al bot i trobes diferents opcions: 
Amarino (Groc)
Smol (Rosa)
Raranga (taronja)
Al clickar una d'aquestes opcions, el teu nom canviarà de color automaticament. 
D'altra banda, la segona part seria la de crear rols especifics per  els nostres pronoms, d'aquesta manera, al obrir el perfil d'uni membre del cibercasal, podriem veure directament amb quins pronoms prefereix ser referida. Això es faria des d'aquest bot de rols també. 
Exemple:
(quadrat):  Ella
(cercle): Elli. 
(Triangle): cap
Suposem que t'identifiques com a "elli", cliques al cercle, i al fer-ho, al teu perfil sortiras amb aquest pronom, i així totis les membres del cibercasal sabran com s'han de referir a tu.

**Comment by vicky5124** [comment]
La proposta ja ha sigut implementada.
